const message = {
    mss_001: 'Ya existe una pizza con ese nombre',
    mss_002: 'La pizza esta disponible',
    mss_003: 'No es un id válido',
    mss_004: 'El nombre es obligatorio',
    mss_005: 'El precio es obligatorio',
    mss_006: 'No es un id válido',
    mss_007: 'Usuario / Password no son correctas',
    mss_008: 'Hable con el administrador',
    mss_009: 'El rol no existe',
    mss_010: 'El correo ya esta registrado',
    mss_011: 'El id no existe',
    mss_012: 'No se pudo generar el token',
    mss_013: 'No hay token en la petición',
    mss_014: 'Token no válido',
    mss_015: 'Se quiere verificar el role sin validar el token primero',
    mss_016: 'No es administrador',
    mss_017: 'El servicio requiere uno de estos roles:',
    mss_018: 'El correo es obligatorio',
    mss_019: 'La contraseña es obligatoria',
    mss_020: 'La pizza no esta disponible',
    mss_021: 'No tienes permisos para realizar esta operacion',
    mss_022: 'No tienes permisos para actualizar otro usuario(token pertenece a otro usuario)',
    mss_023: 'No se ha encontrado ninguna pizza',
    mss_024: 'La compra no esta disponible',
    mss_025: 'La direccion es obligatoria',
    mss_026: 'El usuario no esta disponible',
    mss_027: '',
    mss_028: '',
    mss_029: '',
    mss_030: '',
}

module.exports = {
    message
};